import smtplib
from email.mime.text import MIMEText
from twilio.rest import Client


def send_email(to_address, subject, message, smtp_username, app_password):
    smtp_server = 'smtp.gmail.com'
    smtp_port = 587

    msg = MIMEText(message)
    msg['Subject'] = subject
    msg['From'] = smtp_username
    msg['To'] = to_address

    server = smtplib.SMTP(smtp_server, smtp_port)
    server.starttls()

    try:

        server.login(smtp_username, app_password)

        server.sendmail(smtp_username, to_address, msg.as_string())
        print("Email sent successfully!")

    except smtplib.SMTPAuthenticationError:
        print("Failed to authenticate. Please check your App Password.")

    finally:

        server.quit()


def send_sms(to_number, message, twilio_account_sid, twilio_auth_token, twilio_phone_number):
    client = Client(twilio_account_sid, twilio_auth_token)

    client.messages.create(
        to=to_number,
        from_=twilio_phone_number,
        body=message
    )
    print("SMS sent successfully!")


if __name__ == "__main__":
    app_password = 'scob zeix geus iaof'

    email_smtp_username = 'bharatinnovators550@gmail.com'
    twilio_account_sid = 'AC30da0664a208c5e59e10cbdaff650480'
    twilio_auth_token = 'ba9a2405f1a255c0d753b03f993e0d91'
    twilio_phone_number = '+14707984925'

    custom_message = "This is a message generated by the Police department of Rajasthan in account of a crime that has happened in your area nearly 3 days ago. So we request you to send the video footage of CCTV for the past three days as it will be helpful for our investigation.\n Thank you.\n\n upload your video by filling the following form : https://docs.google.com/forms/d/1X7uab7EHtdp7_LYY886FcYj0fIBsj34zIkCh2smV7Ig/edit?pli=1"

    mobile_number = input("Enter mobile number: ")
    email_address = input("Enter email address: ")

    send_email(email_address, "Regarding uploading of video footage evidence on account of crime in your area",
               custom_message, email_smtp_username, app_password)

    send_sms(mobile_number, custom_message, twilio_account_sid, twilio_auth_token, twilio_phone_number)